version: '3.8'
services:
  mongodb:
    image: mongo:6.0.5
    # container_name: mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: P@ssw0rd
      MONGO_INITDB_DATABASE: supportdesk
    volumes:
      # Uncomment the following line if you want to persist the data in the db folder
      # - ./db:/data/db
      - ./db/initdb:/docker-entrypoint-initdb.d
    networks:
      - support-desk
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # container_name: support-desk-api
    restart: on-failure
    ports:
      - '3001:3001'
    environment:
      # We are redefining the whole connection string
      VITE_MONGODB_URI: mongodb://supportdesk:Password@mongodb:27017/supportdesk?retryWrites=true&w=majority
    volumes:
      - ./backend/src:/app/src
    networks:
      - support-desk
    depends_on:
      - mongodb
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # container_name: support-desk-client
    restart: on-failure
    ports:
      - '3000:3000'
    environment:
      VITE_API_URL: http://api:3001/api
    stdin_open: true
    volumes:
      - ./frontend/src:/app/src
    networks:
      - support-desk
    depends_on:
      - api
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 8080:80
    networks:
      - support-desk
    depends_on:
      - client
      - api
networks:
  support-desk:
    driver: bridge
